### ISSUE TITLE
crash in frame.py

### ISSUE THREAD

**Issue by remdragon** [joerick/pyinstrument#122]
I'm using gevent + flask + pyinstrument + pyinstaller and experiencing a crash when trying to profile my frozen code in the wild.

Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:23:07) [MSC v.1927 32 bit (Intel)] on win32

Here's my proposed fix:
```
# pyinstrument==3.4.1/frame.py line 277:
                library = (frame.file_path_short or '').split(os.sep)[0]
```

Here's the crash:
```
Traceback (most recent call last):
  File "flask\app.py", line 2447, in wsgi_app
  File "flask\app.py", line 1952, in full_dispatch_request
  File "flask\app.py", line 1821, in handle_user_exception
  File "flask\_compat.py", line 39, in reraise
  File "flask\app.py", line 1950, in full_dispatch_request
  File "flask\app.py", line 1936, in dispatch_request
[CENSORED]
  File "pyinstrument\util.py", line 37, in caller
  File "pyinstrument\profiler.py", line 106, in output_text
  File "pyinstrument\renderers\console.py", line 26, in render
  File "pyinstrument\renderers\console.py", line 95, in render_frame
  File "pyinstrument\renderers\console.py", line 95, in render_frame
  File "pyinstrument\renderers\console.py", line 95, in render_frame
  [Previous line repeated 9 more times]
  File "pyinstrument\renderers\console.py", line 77, in render_frame
  File "pyinstrument\frame.py", line 277, in libraries
AttributeError: 'NoneType' object has no attribute 'split'
```

Here's my pip freeze:
```
aiofiles==0.5.0
aiohttp==3.6.3
altgraph==0.17
anyio==2.0.2
argon2-cffi==20.1.0
arrow==0.17.0
async-generator==1.10
async-timeout==3.0.1
attrs==20.2.0
Authlib==0.15.2
Automat==20.2.0
Babel==2.9.0
backcall==0.2.0
bbcode==1.1.0
bcrypt==3.2.0
bleach==3.2.2
certifi==2020.6.20
cffi==1.14.3
chardet==3.0.4
click==7.1.2
colorama==0.4.4
constantly==15.1.0
coverage==5.3
cryptography==3.1.1
Cython==0.29.21
decorator==4.4.2
defusedxml==0.6.0
dnspython==2.0.0
entrypoints==0.3
Flask==1.1.2
Flask-Sockets==0.2.1
future==0.18.2
gevent @ file:///C:/users/roy/Downloads/gevent-20.9.0-cp39-cp39-win32.whl
gevent-websocket==0.10.1
greenlet @ file:///C:/users/roy/Downloads/greenlet-0.4.17-cp39-cp39-win32.whl
grequests==0.6.0
hyperlink==20.0.1
idna==2.10
incremental==17.5.0
ipykernel==5.4.3
ipython==7.19.0
ipython-genutils==0.2.0
itsdangerous==1.1.0
jedi==0.18.0
Jinja2==2.11.2
json-spec==0.10.1
json5==0.9.5
jsoncomment==0.4.2
jsonschema==3.2.0
jupyter-client==6.1.11
jupyter-core==4.7.0
jupyter-server==1.2.2
jupyterlab==3.0.5
jupyterlab-pygments==0.1.2
jupyterlab-server==2.1.2
lark-parser==0.10.1
MarkupSafe==1.1.1
mistune==0.8.4
mock==4.0.2
multidict==4.7.6
mypy==0.790
mypy-extensions==0.4.3
names==0.3.0
nbclassic==0.2.6
nbclient==0.5.1
nbconvert==6.0.7
nbformat==5.1.2
nest-asyncio==1.4.3
netaddr==0.8.0
notebook==6.2.0
packaging==20.8
pandocfilters==1.4.3
paramiko==2.7.2
parso==0.8.1
pathlib==1.0.1
peewee==3.14.0
pefile==2019.4.18
pickleshare==0.7.5
Pillow==8.0.1
prometheus-client==0.9.0
prompt-toolkit==3.0.14
psutil==5.7.2
psycopg2==2.8.6
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pyflakes==2.2.0
Pygments==2.7.4
PyHamcrest==2.0.2
pyinstaller==4.0
pyinstaller-hooks-contrib==2020.9
pyinstrument==3.4.1
pyinstrument-cext==0.2.2
pymsteams==0.1.14
PyMySQL==0.10.1
PyNaCl==1.4.0
pyodbc @ file:///C:/users/roy/Downloads/pyodbc-4.0.30-cp39-cp39-win32.whl
pyOpenSSL==19.1.0
pyparsing==2.4.7
pyrsistent==0.17.3
python-dateutil==2.2
python-ldap @ file:///C:/users/roy/Downloads/python_ldap-3.3.1-cp39-cp39-win32.whl
pytz==2021.1
pyvmomi==7.0.1
pywin32==300
pywin32-ctypes==0.2.0
pywinpty @ file:///C:/Users/roy/Downloads/pywinpty-0.5.7-cp39-cp39-win32.whl
pyzmq==21.0.1
reportlab==3.5.55
requests==2.24.0
requests-mock==1.8.0
Send2Trash==1.5.0
service-identity==18.1.0
simple-salesforce==1.10.1
six==1.15.0
sniffio==1.2.0
termcolor==1.1.0
terminado==0.9.2
testpath==0.4.4
tornado==6.1
traitlets==5.0.5
Twisted @ file:///C:/users/roy/Downloads/Twisted-20.3.0-cp39-cp39-win32.whl
typed-ast==1.4.1
typing-extensions==3.7.4.3
tzlocal==2.1
unicodecsv==0.14.1
urllib3==1.25.10
wcwidth==0.2.5
webencodings==0.5.1
Werkzeug==1.0.1
ws4py==0.5.1
wsman==0.9.27
XlsxWriter==1.3.7
yarl==1.5.1
zope.event==4.5.0
zope.interface==5.1.2
```

**Comment by joerick** [comment]
Hi @remdragon ! I don't support you'd be able to provide a pyireport for a session that causes the crash, or a minimal reproduction perhaps?

**Comment by joerick** [comment]
Closed due to inactivity. Let me know if you can provide a reproduction!
