### ISSUE TITLE
Error with Pyinstrument 4.0.2: ValueError: target not found in subscribers

### ISSUE THREAD

**Issue by ndodda-amazon** [joerick/pyinstrument#139]
Python Version: 3.7.10

OS: Ubuntu 18.04.5

Steps to reproduce:

```
pip install pyinstrument==4.0.2
python test.py
```

where `test.py` is:

```
import pyinstrument
import time
import threading

from pyinstrument import Profiler

profiler = Profiler()

profiler.start()

def helper():
    time.sleep(1)
    profiler.stop()

t1 = threading.Thread(target=helper)
t1.start()
t1.join()

profiler.output_html()
```

And the full stack trace of the error is:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyinstrument/stack_sampler.py", line 73, in unsubscribe
    subscriber = next(s for s in self.subscribers if s.target == target)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "test.py", line 13, in helper
    profiler.stop()
  File "/usr/local/lib/python3.7/site-packages/pyinstrument/profiler.py", line 146, in stop
    get_stack_sampler().unsubscribe(self._sampler_saw_call_stack)
  File "/usr/local/lib/python3.7/site-packages/pyinstrument/stack_sampler.py", line 75, in unsubscribe
    raise ValueError("target not found in subscribers")
ValueError: target not found in subscribers

Traceback (most recent call last):
  File "test.py", line 19, in <module>
    profiler.output_html()
  File "/usr/local/lib/python3.7/site-packages/pyinstrument/profiler.py", line 295, in output_html
    return renderers.HTMLRenderer(timeline=timeline).render(self.last_session)
  File "/usr/local/lib/python3.7/site-packages/pyinstrument/renderers/html.py", line 35, in render
    session_json = self.render_json(session)
  File "/usr/local/lib/python3.7/site-packages/pyinstrument/renderers/html.py", line 83, in render_json
    return json_renderer.render(session)
  File "/usr/local/lib/python3.7/site-packages/pyinstrument/renderers/jsonrenderer.py", line 53, in render
    frame = self.preprocess(session.root_frame())
AttributeError: 'NoneType' object has no attribute 'root_frame'
```

Additional Notes:
The error does not occur with pyinstrument 3.4.2 or an earlier version. Is this use case with pyinstrument not supported anymore? Does the profiler object need to be explicitly stopped before being accessed by a subprocess?

Please let me know if you need any additional information to debug this error.

**Comment by joerick** [comment]
Thanks for the minimal recreation. Firstly, I'll do something about that error message, it's pretty nasty.

As for the issue at hand, I'm quite surprised that it did even work in previous versions! pyinstrument calls [`PyEval_SetProfile`](https://docs.python.org/3/c-api/init.html#c.PyEval_SetProfile) to start/stop, which sets the thread's profiling function, so stopping the profiler in a different thread would leave the first thread still profiling.

I'll do a bit of digging to see if there's a way around it...

**Comment by joerick** [comment]
Hi again. I think there's a way to resolve it, but it would add complexity so I'm trying to figure out if it's worth it. Is this an important use case for you @ndodda-amazon ? Perhaps you could outline why you're using the profiler in this way?

**Comment by joerick** [comment]
Feel free to reopen if you want to continue the chat!
