### ISSUE TITLE
Getting IOError

### ISSUE THREAD

**Issue by rahul-paul** [joerick/pyinstrument#16]
rahul@rahul-desktop { ~/pycharm-workspace/ceres_new }-> python -m pyinstrument ceres/sim/sim_definition.py
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/rahul/src/pyinstrument/pyinstrument/__main__.py", line 135, in <module>
    main()
  File "/home/rahul/src/pyinstrument/pyinstrument/**main**.py", line 79, in main
    exec_(code, globs, None)
  File "/home/rahul/src/pyinstrument/pyinstrument/**main**.py", line 25, in exec_
    exec("exec _code_ in _globs_, _locs_")
  File "<string>", line 1, in <module>
  File "ceres/sim/sim_definition.py", line 48, in <module>
    main()
  File "ceres/sim/sim_definition.py", line 31, in main
    from aglyph.assembler import Assembler
  File "/usr/local/lib/python2.7/dist-packages/aglyph/**init**.py", line 61, in <module>
    platform.platform()))
  File "/usr/lib/python2.7/platform.py", line 1576, in platform
    system,node,release,version,machine,processor = uname()
  File "/usr/lib/python2.7/platform.py", line 1273, in uname
    processor = _syscmd_uname('-p','')
  File "/usr/lib/python2.7/platform.py", line 1029, in _syscmd_uname
    output = string.strip(f.read())
IOError: [Errno 4] Interrupted system call
Alarm clock

**Comment by joerick** [comment]
Really hoping that [PEP 475](https://www.python.org/dev/peps/pep-0475/) makes it into Python 3.5. That could solve this once and for all.
