### ISSUE TITLE
[bug] pyinstruments not working TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by PabloRuizCuevas** [joerick/pyinstrument#297]
I found a bug that pyinstrument not to work at all, I think it may be related with my logger configuration, but I'm not sure. this is the error:

```
Traceback (most recent call last):
  File "C:\Users\PabloRuiz\AppData\Local\Programs\Python\Python311\Lib\logging\__init__.py", line 845, in _removeHandlerRef
  File "C:\Users\PabloRuiz\AppData\Local\Programs\Python\Python311\Lib\logging\__init__.py", line 845, in _removeHandlerRef
  File "C:\Users\PabloRuiz\AppData\Local\pypoetry\Cache\virtualenvs\transformer-wi-nHELc-py3.11\Lib\site-packages\pyinstrument\stack_sampler.py", line 134, in _sample
  File "C:\Users\PabloRuiz\AppData\Local\pypoetry\Cache\virtualenvs\transformer-wi-nHELc-py3.11\Lib\site-packages\pyinstrument\stack_sampler.py", line 148, in _timer
TypeError: 'NoneType' object is not callable
```

**Comment by joerick** [comment]
Sorry for the delay, but I'll need a recreation to really work on this.

**Comment by rtkefreure** [comment]
I hit this problem recently. It only happened when I enabled profiling in code using the `start` and `stop` methods.
```
self._profile = Profiler()
self._profile.start()
...
self._profile.stop()
with open(
  f'/speedscope.json',
  'w',
  encoding='utf-8'
) as f:
  f.write(self._profile.output(renderer=SpeedscopeRenderer(show_all=True)))
...

I was able to work around the error by running the profiler using the `pyinstrument` command instead of enabling the profiler in code.

**Comment by joerick** [comment]
Please feel free to reopen if you manage to find a recreation!
