### ISSUE TITLE
html js file render UnicodeDecodeError

### ISSUE THREAD

**Issue by hgalytoby** [joerick/pyinstrument#329]
When I use another package library, the other library uses pyinstrument.

I traced the code from

https://github.com/joerick/pyinstrument/blob/main/pyinstrument/renderers/html.py#L44

Using `read_text`

https://github.com/python/cpython/blob/3.12/Lib/pathlib.py#L1022

I have a `UnicodeDecodeError: 'cp950' codec can't decode byte 0xc2 in position 12675: illegal multibyte sequence`.

If the

` js = js_file.read_text()` to ` js = js_file.read_text(encoding='utf-8')` will solve the problem.

Is there any other way?

```py
Traceback (most recent call last):
  File "C:\Users\duduru\AppData\Local\pypoetry\Cache\virtualenvs\backend-Clwg8yIO-py3.10\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\duduru\AppData\Local\pypoetry\Cache\virtualenvs\backend-Clwg8yIO-py3.10\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\duduru\AppData\Local\pypoetry\Cache\virtualenvs\backend-Clwg8yIO-py3.10\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\duduru\AppData\Local\pypoetry\Cache\virtualenvs\backend-Clwg8yIO-py3.10\lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\duduru\AppData\Local\pypoetry\Cache\virtualenvs\backend-Clwg8yIO-py3.10\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\duduru\AppData\Local\pypoetry\Cache\virtualenvs\backend-Clwg8yIO-py3.10\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\duduru\AppData\Local\pypoetry\Cache\virtualenvs\backend-Clwg8yIO-py3.10\lib\site-packages\starlette\middleware\base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\Users\duduru\AppData\Local\pypoetry\Cache\virtualenvs\backend-Clwg8yIO-py3.10\lib\site-packages\debug_toolbar\middleware.py", line 84, in dispatch
    await toolbar.record_stats(response)
  File "C:\Users\duduru\AppData\Local\pypoetry\Cache\virtualenvs\backend-Clwg8yIO-py3.10\lib\site-packages\debug_toolbar\toolbar.py", line 91, in record_stats
    async with create_task_group() as tg:
  File "C:\Users\duduru\AppData\Local\pypoetry\Cache\virtualenvs\backend-Clwg8yIO-py3.10\lib\site-packages\anyio\_backends\_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "C:\Users\duduru\AppData\Local\pypoetry\Cache\virtualenvs\backend-Clwg8yIO-py3.10\lib\site-packages\debug_toolbar\panels\__init__.py", line 88, in record_stats
    stats = await self.generate_stats(request, response)
  File "C:\Users\duduru\AppData\Local\pypoetry\Cache\virtualenvs\backend-Clwg8yIO-py3.10\lib\site-packages\debug_toolbar\panels\profiling.py", line 32, in generate_stats
    return {"content": self.profiler.output_html()}
  File "C:\Users\duduru\AppData\Local\pypoetry\Cache\virtualenvs\backend-Clwg8yIO-py3.10\lib\site-packages\pyinstrument\profiler.py", line 364, in output_html
    return self.output(
  File "C:\Users\duduru\AppData\Local\pypoetry\Cache\virtualenvs\backend-Clwg8yIO-py3.10\lib\site-packages\pyinstrument\profiler.py", line 398, in output
    return renderer.render(session)
  File "C:\Users\duduru\AppData\Local\pypoetry\Cache\virtualenvs\backend-Clwg8yIO-py3.10\lib\site-packages\pyinstrument\renderers\html.py", line 45, in render
    js = js_file.read_text()
  File "C:\Users\duduru\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1135, in read_text
    return f.read()
UnicodeDecodeError: 'cp950' codec can't decode byte 0xc2 in position 12675: illegal multibyte sequence

```

**Comment by joerick** [comment]
Send a PR with that change! Perhaps there's a weird character in the file now, but everything is utf8
