### ISSUE TITLE
"SystemError: <built-in function get_frame_info> returned a result with an exception set" when running with pytest

### ISSUE THREAD

**Issue by marcinbarczynski** [joerick/pyinstrument#331]
When I run pyinstrument with pytest, I get the following exception right after start:
```
$ pyinstrument  -m pytest --long path/to/my/test.py::TestFoo
/home/q/.virtualenvs/myenv/lib/python3.12/site-packages/_pytest/config/__init__.py:328: PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown.
Plugin: helpconfig, Hook: pytest_cmdline_parse
SystemError: <built-in function get_frame_info> returned a result with an exception set
For more information see https://pluggy.readthedocs.io/en/stable/api_reference.html#pluggy.PluggyTeardownRaisedWarning
  config = pluginmanager.hook.pytest_cmdline_parse(
KeyError: 'cls'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/q/.virtualenvs/myenv/bin/pyinstrument", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/q/.virtualenvs/myenv/lib/python3.12/site-packages/pyinstrument/__main__.py", line 382, in main
    exec(code, globs, None)
  File "<string>", line 1, in <module>
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/home/q/.virtualenvs/myenv/lib/python3.12/site-packages/pytest/__main__.py", line 5, in <module>
    raise SystemExit(pytest.console_main())
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/q/.virtualenvs/myenv/lib/python3.12/site-packages/_pytest/config/__init__.py", line 189, in console_main
    code = main()
           ^^^^^^
  File "/home/q/.virtualenvs/myenv/lib/python3.12/site-packages/_pytest/config/__init__.py", line 147, in main
    config = _prepareconfig(args, plugins)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/q/.virtualenvs/myenv/lib/python3.12/site-packages/_pytest/config/__init__.py", line 328, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/q/.virtualenvs/myenv/lib/python3.12/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/q/.virtualenvs/myenv/lib/python3.12/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/q/.virtualenvs/myenv/lib/python3.12/site-packages/pluggy/_callers.py", line 156, in _multicall
    teardown[0].send(outcome)
  File "/home/q/.virtualenvs/myenv/lib/python3.12/site-packages/_pytest/helpconfig.py", line 103, in pytest_cmdline_parse
    config: Config = outcome.get_result()
                     ^^^^^^^^^^^^^^^^^^^^
  File "/home/q/.virtualenvs/myenv/lib/python3.12/site-packages/pluggy/_result.py", line 100, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/home/q/.virtualenvs/myenv/lib/python3.12/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/q/.virtualenvs/myenv/lib/python3.12/site-packages/_pytest/config/__init__.py", line 1077, in pytest_cmdline_parse
    self.parse(args)
  File "/home/q/.virtualenvs/myenv/lib/python3.12/site-packages/_pytest/config/__init__.py", line 1366, in parse
    self._preparse(args, addopts=addopts)
  File "/home/q/.virtualenvs/myenv/lib/python3.12/site-packages/_pytest/config/__init__.py", line 1249, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/home/q/.virtualenvs/myenv/lib/python3.12/site-packages/pluggy/_manager.py", line 421, in load_setuptools_entrypoints
    plugin = ep.load()
             ^^^^^^^^^
  File "/opt/starfish/python3.12/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/starfish/python3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed

<my code base>

  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1124, in get_code
  File "<frozen importlib._bootstrap_external>", line 753, in _compile_bytecode
  File "<frozen importlib._bootstrap_external>", line 753, in _compile_bytecode
  File "/home/q/.virtualenvs/myenv/lib/python3.12/site-packages/pyinstrument/stack_sampler.py", line 194, in _sample
    call_stack = build_call_stack(frame, event, arg)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/q/.virtualenvs/myenv/lib/python3.12/site-packages/pyinstrument/stack_sampler.py", line 300, in build_call_stack
    call_stack.append(get_frame_info(frame))
                      ^^^^^^^^^^^^^^^^^^^^^
SystemError: <built-in function get_frame_info> returned a result with an exception set
```
Function from my code base included in tracebacks change between executions.

The tests run without any problem if pyinstrument is not used.
Setting a larger interval, e.g. `--interval 0.01` resolves the issue.

Configuration:
```
$ python --version
Python 3.12.4

$ pip freeze | grep "pyinstrument\|pytest"
pyinstrument==4.7.2
pytest==7.3.2
pytest-cases==3.8.5
pytest-custom-exit-code==0.3.0
pytest-flakefinder==1.1.0
pytest-memray==1.7.0
pytest-mock==3.10.0
pytest-parallelize-tests==0.2
pytest-random-order==1.1.1
pytest-subtests==0.13.1
pytest-testconfig==0.2.0
```

**Comment by joerick** [comment]
This must be an error in the C extension, I'll have a look

**Comment by joerick** [comment]
This change was made for Python 3.13 compatibility, it seems PyDict_GetItem doesn't raise an error where PyObject_GetItem does. Fix is simple but might take a few days. 

I'm curious of the root cause though. If anyone can make a minimal reproducer, that would be great. Essentially the problem is that a function has a local called 'cls' (according to the code) but when the extension reads locals()['cls'] at runtime it's not there.

**Comment by marcinbarczynski** [comment]
> I'm curious of the root cause though. If anyone can make a minimal reproducer, that would be great. Essentially the problem is that a function has a local called 'cls' (according to the code) but when the extension reads locals()['cls'] at runtime it's not there.

I tried but to no avail. It looks like a problem in pytest stock plugin, but I can't see `cls` arguments around the problematic line.

**Comment by joerick** [comment]
If you're interested, I managed to make a reproducer-

```python
import time


class A:
    @classmethod
    def class_method(cls):
        print('class_method')
        del cls
        time.sleep(0.1)

A.class_method()
```

I'll get it fixed.

**Comment by jucor** [comment]
Thanks for the diligence in investigating!!

**Comment by jucor** [comment]
Wow, that was fast!

**Comment by marcinbarczynski** [comment]
Thanks a lot! :+1: :+1: :+1:

**Comment by sander76** [comment]
@joerick This fix has not been released has it ? I have this same issue.
