### ISSUE TITLE
OSError: [Errno 36] File name too long

### ISSUE THREAD

**Issue by laurentbetti** [joerick/pyinstrument#50]
When using ProfilerMiddleware (pyinstrument 2.2.1) with Django (1.11.9), when profiling view related to an API endpoint that accepts very long GET querystring, I get the following error:

    Traceback (most recent call last):
      File "/home/laurent/.pyenv/versions/my_app/lib/python3.6/site-packages/django/core/handlers/base.py", line 131, in get_response
        response = middleware_method(request, response)
       File "/home/laurent/.pyenv/versions/my_app/lib/python3.6/site-packages/pyinstrument/middleware.py", line 43, in process_response
        with open(file_path, 'w') as f:
    OSError: [Errno 36] File name too long: 'profiles/2.279s _api_v1_translations_?word=comes&orig...[A_VERY_LONG_QUERYSTRING]'

I guess that the profile file name length could be truncated at some point in this module code.

**Comment by joerick** [comment]
absolutely - filename truncation sounds right. PR welcome!

**Comment by laurentbetti** [comment]
Done! #51

**Comment by joerick** [comment]
Released in v2.3.0!
