### ISSUE TITLE
UnicodeEncodeError when writing html

### ISSUE THREAD

**Issue by ChillarAnand** [joerick/pyinstrument#73]
```
- - - [2019-11-13 05:17:27,813] "- - -" - [ERROR:django.request:256] Internal Server Error: /api/v1/logout
Traceback (most recent call last):
  File "/Users/anand/.local/share/virtualenvs/avilpage-pc50wcPX/lib/python2.7/site-packages/django/core/handlers/base.py", line 223, in get_response
    response = middleware_method(request, response)
  File "/Users/anand/.local/share/virtualenvs/avilpage-pc50wcPX/lib/python2.7/site-packages/pyinstrument/middleware.py", line 53, in process_response
    f.write(output_html)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 87794: ordinal not in range(128)
[13/Nov/2019 05:17:27] "POST /api/v1/logout HTTP/1.1" 500 95880
```

When adding middleware to django and writing html to profiles directory, it is failing with unicode encode error.

**Comment by joerick** [comment]
Guessing this needs an `io.open(..., encoding='utf8')`. Happy to accept a PR to fix this!
