### ISSUE TITLE
pyinstrument_cext cannot be imported using conda environments 

### ISSUE THREAD

**Issue by anktkr** [joerick/pyinstrument#86]
This is a continuation of the ticket #37
I tried multiple methods, before, as a last option, building source. But that too failed. 

```
import sys
sys.path.append("/Users/me/opt/anaconda3/envs/ee/lib/python3.7/site-packages")
sys.path.append("/Users/me/Applications/pyinstrument-3.1.3/")
import pyinstrument
profiler = Profiler()
```
```
Traceback (most recent call last):
  File "/Users/me/Desktop/stack.py", line 5, in <module>
    import pyinstrument
  File "/Users/me/Applications/pyinstrument-3.1.3/pyinstrument/__init__.py", line 1, in <module>
    from pyinstrument.profiler import Profiler
  File "/Users/me/Applications/pyinstrument-3.1.3/pyinstrument/profiler.py", line 6, in <module>
    from pyinstrument_cext import setstatprofile
ImportError: No module named pyinstrument_cext
```
I installed pyinstrument_cext in the conda environment multiple times using both `/Users/me/opt/anaconda3/envs/ee/bin/pip` and conda using the channel `conda-forge`. 

```
conda list pyinstrument_cext
# packages in environment at /Users/me/opt/anaconda3/envs/ee:
#
# Name                    Version                   Build  Channel
pyinstrument_cext         0.2.2            py37h0b31af3_0    conda-forge
```

**Comment by anktkr** [comment]
It worked after a reinstall
